version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker_a:
    image: celery-demo:latest
    command: celery -A app worker --loglevel=info -Q a_queue
    # command: sleep infinity
    volumes:
      - ./app:/code/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  worker_b:
    image: celery-demo:latest
    command: celery -A app worker --loglevel=info -Q b_queue
    volumes:
      - ./app:/code/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
